name: indopay
description: INDOPAY Agen Pulsa & PPOB
publish_to: 'none' # private project
version: 1.0.0+1

environment:
  sdk: ">=2.20.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.10.0
  provider: ^6.0.6
  http: ^1.1.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.1.1

flutter:
  uses-material-design: true
